### ISSUE TITLE
Exception in NavActivity

### ISSUE THREAD

**Issue by doerfli** [doerfli/hacked#118]
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://haveibeenpwned.com/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2100)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1742)
       at android.app.Activity.startActivityForResult(Activity.java:4594)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:4552)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:4917)
       at android.app.Activity.startActivity(Activity.java:4885)
       at li.doerf.hacked.activities.NavActivity.onOptionsItemSelected(NavActivity.kt:49)
       at android.app.Activity.onMenuItemSelected(Activity.java:3551)
       at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
       at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
       at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
       at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
       at android.widget.AdapterView.performItemClick(AdapterView.java:318)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3162)
       at android.widget.AbsListView$3.run(AbsListView.java:4078)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6936)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

https://console.firebase.google.com/u/0/project/hackedapp-75421/crashlytics/app/android:li.doerf.hacked/issues/c4542e1f403c046ac4c093f258e2bb85?time=last-thirty-days&sessionId=5E61E3DF02950001321E5730E02A9919_DNE_0_v2

**Comment by doerfli** [comment]
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://doerfli.github.io/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2031)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1686)
       at android.app.Activity.startActivityForResult(Activity.java:4506)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:4464)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:4829)
       at android.app.Activity.startActivity(Activity.java:4797)
       at li.doerf.hacked.activities.NavActivity.onOptionsItemSelected(NavActivity.kt:44)
       at android.app.Activity.onMenuItemSelected(Activity.java:3469)
       at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
       at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
       at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
       at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
       at android.widget.AdapterView.performItemClick(AdapterView.java:318)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3153)
       at android.widget.AbsListView$3.run(AbsListView.java:4068)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6647)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

https://console.firebase.google.com/u/0/project/hackedapp-75421/crashlytics/app/android:li.doerf.hacked/issues/5068fba4a4b76a0754a6b8804272c244?time=last-thirty-days&sessionId=5E629B83004900014DDA552C26AA766A_DNE_0_v2
