### ISSUE TITLE
Exception in OverviewFragment

### ISSUE THREAD

**Issue by doerfli** [doerfli/hacked#119]
```
Fatal Exception: java.lang.IllegalStateException: Fragment OverviewFragment{42b053d8} (28ed5804-0c53-4db8-bbf9-f893837f9744)} not associated with a fragment manager.
       at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:945)
       at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:107)
       at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)
       at li.doerf.hacked.ui.fragments.OverviewFragment$onStart$1$1.invokeSuspend(OverviewFragment.kt:33)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

https://console.firebase.google.com/u/0/project/hackedapp-75421/crashlytics/app/android:li.doerf.hacked/issues/cdb62b0732a39d764c241a9ab8d33d64?time=last-thirty-days&sessionId=5E59C07F00CE0001369C9342A09F5D6B_DNE_0_v2

**Comment by doerfli** [comment]
could not reproduce
