### ISSUE TITLE
KotlinNullPointerException in AccountDetailsFragment

### ISSUE THREAD

**Issue by doerfli** [doerfli/hacked#127]
```
Fatal Exception: kotlin.KotlinNullPointerException
       at li.doerf.hacked.ui.fragments.AccountDetailsFragment$onCreateView$2.accept(AccountDetailsFragment.kt:63)
       at li.doerf.hacked.ui.fragments.AccountDetailsFragment$onCreateView$2.accept(AccountDetailsFragment.kt:36)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Comment by doerfli** [comment]
https://console.firebase.google.com/u/0/project/hackedapp-75421/crashlytics/app/android:li.doerf.hacked/issues/5640f8135b72d7117cb73fb54adcb523?time=last-seven-days&sessionId=5E6B5601039600014891759103E1A617_DNE_0_v2
