### ISSUE TITLE
SocketException in PwnedPassword

### ISSUE THREAD

**Issue by doerfli** [doerfli/hacked#128]
```
Caused by java.net.SocketException: socket is closed
       at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@19275019@19.2.75 (040400-269183835):8)
       at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
       at com.android.okhttp.okio.RealBufferedSource.request(RealBufferedSource.java:71)
       at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
       at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
       at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
       at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
       at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
       at com.android.okhttp.okio.InflaterSource.refill(InflaterSource.java:101)
       at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:62)
       at com.android.okhttp.okio.GzipSource.read(GzipSource.java:80)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
       at java.io.FilterInputStream.read(FilterInputStream.java:133)
       at com.github.kittinunf.fuel.util.ProgressInputStream.read(ProgressInputStream.kt:46)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
       at java.io.FilterInputStream.read(FilterInputStream.java:107)
       at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
       at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
       at com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:87)
       at com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:50)
       at com.github.kittinunf.fuel.core.Response.getData(Response.kt:32)
       at com.github.kittinunf.fuel.core.deserializers.StringDeserializer.deserialize(StringDeserializer.kt:8)
       at com.github.kittinunf.fuel.core.deserializers.StringDeserializer.deserialize(StringDeserializer.kt:7)
       at com.github.kittinunf.fuel.core.DeserializableKt.serializeFor(Deserializable.kt:259)
       at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:250)
       at li.doerf.hacked.remote.pwnedpasswords.PwnedPassword$checkPassword$$inlined$awaitStringResponseResult$1.invokeSuspend(Coroutines.kt:68)
       at li.doerf.hacked.remote.pwnedpasswords.PwnedPassword$checkPassword$$inlined$awaitStringResponseResult$1.invoke(Coroutines.kt)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
       at kotlinx.coroutines.BuildersKt.withContext(:1)
       at li.doerf.hacked.remote.pwnedpasswords.PwnedPassword.checkPassword(PwnedPassword.kt:111)
       at li.doerf.hacked.remote.pwnedpasswords.PwnedPassword$check$1$1.invokeSuspend(PwnedPassword.kt:38)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by doerfli** [comment]
https://console.firebase.google.com/u/0/project/hackedapp-75421/crashlytics/app/android:li.doerf.hacked/issues/e4aea659d09e0f73bf33f250893d6b6c?time=last-seven-days&sessionId=5E6B71A101A7000128D14F22DF4F9D5F_DNE_0_v2
